apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webserver
  template:
    metadata:
      labels:
        app: my-webserver
    spec:
      containers:
      - name: webserver
        image: nahid003/java-springboot-pipeline:TAG
        env:
        - name: MYSQL_HOST
          value: my-mysql-service
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 8080
